### PR TITLE
Add Mayhem Support

### PR DESCRIPTION
**Pull request by mahaloz**

### CODE REVIEW

**Review by nathanjackson — CHANGES_REQUESTED** [review]
Minor nitpick: please change the target name.

**Comment by mahaloz** [comment]
@nathanjackson done!

**Review by nathanjackson — APPROVED** [review]
LGTM

**Comment by nathanjackson** [comment]
Good work! Someone should be reaching out to you for the next step in the process.

Please continue to monitor this repo for the next 30 days as we will be turning on automatic synchronization with upstream. If the integration breaks in the next 30 days, we'll look to you to fix it. After 30 days, assuming everything still works, you'll be eligible for the $250.

**Pull request merged**
